version: '3'
services:
  a2s_tracker:
    build: a2s_tracker/
    image: a2s_tracker
    restart: always
    container_name: a2s_tracker
    environment:
      SERVERADDR: "endpoint.dlg"
      WEBHOOKURL: "webhookurl"
      CUSTOMMSG: "custommsg"